import type { SystemOSPost } from './types';

export const systemOSSamplePosts: SystemOSPost[] = [
  {
    id: 1,
    title: 'Corporate UI Principles for Admin Systems',
    slug: 'corporate-ui-principles-admin-systems',
    category: 'Operations',
    author: 'Suleiman Msaba',
    status: 'draft',
    updated: '2026-03-23T09:22:00',
    scheduledFor: '',
    publishedAt: '',
    readTime: '5 min read',
    views: 210,
    excerpt: 'A short summary that explains why the article matters.',
    cover: '',
    body: 'Write the article content here.',
    note: '',
    metaTitle: 'SEO title',
    metaDescription: 'Explain the page in one concise paragraph.',
    seo: 74,
  },
  {
    id: 2,
    title: 'Best Admin Tables for Speed',
    slug: 'best-admin-tables-for-speed',
    category: 'Design',
    author: 'Suleiman Msaba',
    status: 'published',
    updated: '2026-03-22T11:16:00',
    scheduledFor: '',
    publishedAt: '2026-03-21T08:30:00',
    readTime: '7 min read',
    views: 1840,
    excerpt: 'How dense tables can stay readable when hierarchy and alignment are handled well.',
    cover: '',
    body: 'This article explains how to make admin tables feel fast, compact, and readable.',
    note: '',
    metaTitle: 'Best admin tables for speed',
    metaDescription: 'A practical guide to dense but usable admin tables.',
    seo: 88,
  },
  {
    id: 3,
    title: 'Scheduling Content Without Friction',
    slug: 'scheduling-content-without-friction',
    category: 'Marketing',
    author: 'Amina Yusuf',
    status: 'scheduled',
    updated: '2026-03-23T07:20:00',
    scheduledFor: '2026-03-25T09:00:00',
    publishedAt: '',
    readTime: '4 min read',
    views: 620,
    excerpt: 'A framework for publishing on time without overloading the team.',
    cover: '',
    body: 'Plan, review, schedule, and track every post in one tight workflow.',
    note: 'Post after homepage banner update.',
    metaTitle: 'Scheduling content without friction',
    metaDescription: 'How editorial teams can schedule content cleanly.',
    seo: 81,
  },
  {
    id: 4,
    title: 'Archived Example Post',
    slug: 'archived-example-post',
    category: 'Business',
    author: 'Editor Team',
    status: 'trash',
    updated: '2026-03-19T12:05:00',
    scheduledFor: '',
    publishedAt: '',
    readTime: '3 min read',
    views: 44,
    excerpt: 'An old post kept only for testing the trash flow.',
    cover: '',
    body: 'Old content.',
    note: '',
    metaTitle: 'Archived example post',
    metaDescription: 'A testing item.',
    seo: 52,
  },
];
